### ISSUE TITLE
Icon request: Visibility

### ISSUE THREAD

**Issue by MMux** [apigee-internal/apigee-icons#11]
Need a finished icon for a hover row for api product publishing:
<img width="434" alt="screen shot 2016-10-07 at 2 39 58 pm" src="https://cloud.githubusercontent.com/assets/1907403/19206196/fd793ea8-8c9b-11e6-994a-0d5a338719e2.png">

**Comment by ichung1** [comment]
Icon created (14pt) in the Sketch file in dropbox.  Marking as done.
