### ISSUE TITLE
Add an icon for feedback in sidenav

### ISSUE THREAD

**Issue by earth2marsh** [apigee-internal/apigee-icons#14]
In order to move the current feedback button out of the default place where it is and into the consistent sidenav, we need an iconic representation of "send feedback". Recommend styling it after Chet's electric megaphone in the San Jose office.

**Comment by ichung1** [comment]
Megaphone has been created in 22pt (14pt as well just in case).  Sketch file has been updated.  

<img width="95" alt="screen shot 2016-10-13 at 11 53 39 am" src="https://cloud.githubusercontent.com/assets/10854635/19362467/b5521146-913b-11e6-9a7a-f0922b2e4dec.png">

Marking done.

**Comment by brandonscript** [comment]
We had a good laugh but I don’t think we can ship it like this -- let's have two of the non-"special" versions of this one too just to be safe ;)

**Comment by ichung1** [comment]
No problem at all.  I saved the "special" ones in the sketch file and labeled them as such.  The originals are in there as well.

<img width="99" alt="screen shot 2016-10-13 at 12 14 46 pm" src="https://cloud.githubusercontent.com/assets/10854635/19363304/cae475a0-913e-11e6-9068-76fdc6df599f.png">
