### ISSUE TITLE
Add mortarboard (university hat) icon for alternative for "learn"

### ISSUE THREAD

**Issue by brandonscript** [apigee-internal/apigee-icons#15]
Should be able to use the stock PL one, just make sure it exports as SVG ok.

**Comment by ichung1** [comment]
14pt/22pt icon added to Sketch file.  Named this "learn-hat" since we already have a "learn". 

<img width="95" alt="screen shot 2016-10-14 at 8 55 02 am" src="https://cloud.githubusercontent.com/assets/10854635/19393996/0735fe0e-91ec-11e6-86cb-8e65a69b341b.png">
