### ISSUE TITLE
Rocket icon is missing its porthole window

### ISSUE THREAD

**Issue by brandonscript** [apigee-internal/apigee-icons#16]
<img width="245" alt="screenshot_1678" src="https://cloud.githubusercontent.com/assets/1480253/19364791/76ecac32-9144-11e6-8868-558f53e36070.png">
![artboard](https://cloud.githubusercontent.com/assets/1480253/19364822/a55f78c4-9144-11e6-9cbd-4a63eb58a41f.png)

**Comment by ichung1** [comment]
Fixed.  Sketch file updated.
