### ISSUE TITLE
Use solar system icon for portals

### ISSUE THREAD

**Issue by brandonscript** [apigee-internal/apigee-icons#17]
Like this:

<img src="https://d30y9cdsu7xlg0.cloudfront.net/png/36931-200.png">

**Comment by ichung1** [comment]
Portal icons created in 22pt/14pt.  Also created in 42pt/30pt for experimentation purposes.  Sketch file updated. 

<img width="257" alt="screen shot 2016-10-21 at 1 13 14 pm" src="https://cloud.githubusercontent.com/assets/10854635/19610230/2704ed9a-9790-11e6-986f-c73e4fde59cf.png">
