### ISSUE TITLE
Need an icon to indicate something is grabbable

### ISSUE THREAD

**Issue by ghost** [apigee-internal/apigee-icons#20]
Should replace the icon left of "Home" below:
<img width="103" alt="screen shot 2016-10-20 at 3 07 35 pm" src="https://cloud.githubusercontent.com/assets/6740693/19579752/18792412-96d7-11e6-86a6-809583af8378.png">

**Comment by ichung1** [comment]
Talked with Rod/Steve on this last week.  Rod apparently has this icon on his end (apic-grab?).  We dont have this in our Sketch file, which we can easily create and put in.

Ok to close ticket per Rod.

**Comment by ichung1** [comment]
Closing ticket.
