### ISSUE TITLE
We must banish `</>` and replace it with `>_`

### ISSUE THREAD

**Issue by jeremyanticouni** [apigee-internal/apigee-icons#21]
The `</>` icon makes pandas sad. Let's go with `>_` instead.

**Comment by ichung1** [comment]
"doc-prompt" and "folder-prompt" with ">_" icon created in Sketch file.  Replaced "</>" to ">_" in the "develop" laptop icon as well.

<img width="212" alt="screen shot 2016-10-21 at 1 07 41 pm" src="https://cloud.githubusercontent.com/assets/10854635/19610124/a1c91c0a-978f-11e6-9eab-9813e1232fd5.png">
