### ISSUE TITLE
New Folder Icon

### ISSUE THREAD

**Issue by jeremyanticouni** [apigee-internal/apigee-icons#23]
Rather than have entity-specific icons for each content view, let's go with a generic folder icon instead.

**Comment by ichung1** [comment]
Icon will be named "folder".

**Comment by ichung1** [comment]
"folder" has been created in 22pt.  Sketch file updated.

<img width="77" alt="screen shot 2016-10-24 at 2 48 00 pm" src="https://cloud.githubusercontent.com/assets/10854635/19665248/f66e9a9e-99f8-11e6-9820-4fda27593e48.png">
