### ISSUE TITLE
Icon request: open in new tab

### ISSUE THREAD

**Issue by MMux** [apigee-internal/apigee-icons#24]
In several portal screens, there are links out to launch the portal. See enclosed.

![create page - editor](https://cloud.githubusercontent.com/assets/1907403/19663910/13fb1d68-99f3-11e6-9871-8acb63e0fdf6.png)

**Comment by ichung1** [comment]
Diagonal arrow (up and to the right).  Text not needed.

<img width="189" alt="screen shot 2016-10-24 at 2 13 12 pm" src="https://cloud.githubusercontent.com/assets/10854635/19664149/094b8c80-99f4-11e6-8502-138916917a2a.png">

**Comment by ichung1** [comment]
Created "open-new-tab" (14pt).  Sketch file updated.

<img width="60" alt="screen shot 2016-10-24 at 4 21 51 pm" src="https://cloud.githubusercontent.com/assets/10854635/19667490/00884e3c-9a06-11e6-9b00-5004ec78490d.png">
