### ISSUE TITLE
Icon request: arrow pointing right

### ISSUE THREAD

**Issue by ghost** [apigee-internal/apigee-icons#25]
As seen in middle of modal below:
![screen shot 2016-10-24 at 4 22 26 pm](https://cloud.githubusercontent.com/assets/6740693/19668336/f71eab38-9a0b-11e6-8632-45a065d9acf9.png)

**Comment by ichung1** [comment]
"arrow-right" (22pt) created.  Sketch file updated.

<img width="70" alt="screen shot 2016-10-24 at 5 21 24 pm" src="https://cloud.githubusercontent.com/assets/10854635/19668705/78791cd4-9a0e-11e6-8064-4bc72b19ad78.png">
