### ISSUE TITLE
Icon: typ-cursor

### ISSUE THREAD

**Issue by jeremyanticouni** [apigee-internal/apigee-icons#27]
Need to get the PL icon `typ-cursor` added; to be used to indicate entity rename.

<img width="74" alt="screen shot 2016-10-27 at 3 22 00 pm" src="https://cloud.githubusercontent.com/assets/1294201/19787715/212ea4e2-9c59-11e6-9017-ac8f37ba5148.png">

**Comment by ichung1** [comment]
"rename-sm" created in 14pt.  Sketch file updated.

<img width="57" alt="screen shot 2016-10-27 at 3 57 35 pm" src="https://cloud.githubusercontent.com/assets/10854635/19788746/0df7ef90-9c5f-11e6-8dee-ade5a33cff72.png">

**Comment by ichung1** [comment]
Icon created in latest 1.0.6 version.  Closing.
