### ISSUE TITLE
Icon: con-toolbox

### ISSUE THREAD

**Issue by jeremyanticouni** [apigee-internal/apigee-icons#28]
The wrench icon will be replaced with con-toolbox

<img width="95" alt="screen shot 2016-10-27 at 3 23 18 pm" src="https://cloud.githubusercontent.com/assets/1294201/19787800/80b8c050-9c59-11e6-9e96-c4a2d7ef7591.png">

**Comment by ichung1** [comment]
"toolbox-sm" 14pt created.  Sketch file updated.

<img width="53" alt="screen shot 2016-10-27 at 4 22 18 pm" src="https://cloud.githubusercontent.com/assets/10854635/19789082/9d5e6fe0-9c61-11e6-8c02-aad7247dd936.png">

**Comment by ichung1** [comment]
Icon created in latest 1.0.6 version.  Closing.
