### ISSUE TITLE
Icon request: Portal homepage blocks

### ISSUE THREAD

**Issue by MMux** [apigee-internal/apigee-icons#30]
For a portal homepage, we have large clickable cards to navigate to the functionality previously located in the context bar switcher. 

We need large sizes (identical to edge landing page) for:

**APIs** (this will be where they add their api products, which we're currently calling apis here)
**Files Manager** (a store for logo files, images and content related to their portal)
**Theme ** (a css editor so customers can skin the portal w/ their own branding)
**Pages** (a list of pages for the customer portal)
**Settings** (allows customers to change their domain, control security features, etc.)
**Menus** (customer will configure and publish their menus: top nav, footer, sidebar menus)
![portal - landing page](https://cloud.githubusercontent.com/assets/1907403/20076502/80b83d6e-a4ed-11e6-895d-cf794815ff04.png)
![menu-builder-snapshot](https://cloud.githubusercontent.com/assets/1907403/20076521/94c59de2-a4ed-11e6-886f-9f1acfbdcaef.png)

**Comment by ichung1** [comment]
Worked with Mike on this.  Icons added.  Sketch file updated.  

<img width="728" alt="screen shot 2016-11-08 at 2 59 19 pm" src="https://cloud.githubusercontent.com/assets/10854635/20120980/fbdabe32-a5c3-11e6-904c-8dc919cf6c47.png">

**Comment by ichung1** [comment]
Icons added in latest build.  Closing.
