### ISSUE TITLE
Icon request: copy to clipboard

### ISSUE THREAD

**Issue by MMux** [apigee-internal/apigee-icons#32]
In analytics, users will have the ability to copy a link to their clipboard.
<img width="1135" alt="screen shot 2016-11-11 at 11 19 46 am" src="https://cloud.githubusercontent.com/assets/1907403/20227319/c7200e6a-a800-11e6-8912-fe00f836d573.png">

**Comment by ichung1** [comment]
Icon created.  Sketch file updated.

<img width="59" alt="screen shot 2016-11-14 at 9 42 01 am" src="https://cloud.githubusercontent.com/assets/10854635/20275792/a5f9c258-aa4e-11e6-9021-d78ed161ddef.png">

**Comment by ichung1** [comment]
Cleaning up old tickets.  Icon created and released in 1.0.7
