### ISSUE TITLE
Request for icon

### ISSUE THREAD

**Issue by ghost** [apigee-internal/apigee-icons#4]
Hi guys,

Can I get a 'close' icon?  Right now I'm using apic-toggle-x to indicate 'close' and it's a bit small/thin.

![screen shot 2016-10-05 at 4 10 29 pm](https://cloud.githubusercontent.com/assets/6740693/19134986/53940c8c-8b16-11e6-8d2a-bf461133499f.png)

**Comment by brandonscript** [comment]
When done, will be `apic-close-sm`

**Comment by ichung1** [comment]
After common consensus, looks like we're getting rid of the "close" element.

Closing ticket.
