### ISSUE TITLE
Wrench icon for (edit actions)

### ISSUE THREAD

**Issue by Manningham** [apigee-internal/apigee-icons#6]
Needed currently for api proxies page for the 'edit revision' button on revision cards.  Using font awesome icon in the meantime:

<img width="594" alt="screen shot 2016-10-06 at 4 41 59 pm" src="https://cloud.githubusercontent.com/assets/12063122/19174497/07834082-8be4-11e6-86b0-dcd5c685e6b8.png">

**Comment by brandonscript** [comment]
Looks like we also need one for the trace icon at 14pt

**Comment by ichung1** [comment]
22pt/14pt wrench created in Sketch file.  14pt trace icon also created.
