### ISSUE TITLE
Icon request: Advisory for Classic UI

### ISSUE THREAD

**Issue by kenigeer** [apigee-internal/apigee-icons#7]
There's going to be a new (simple) Advisory panel on the classic UI. For example, it will say "Your certificate is about to expire!"

Current thinking is something like the bell icon in Gmail for Google Notifications, in the top right next to your mugshot/avatar. Doesn't have to be a bell of course. Three states:
- Get your attention
- No alerts
- Panel open

Click it to toggle the panel. It would go in the menu bar, so it would have to blend well with the orange. Small, maybe to the left of "API Management" or to the right of the "apigee" logo

Code freeze is next Thursday 13 Oct, and having a day or two for revisions would be nice.
<img width="268" alt="screen shot 2016-10-06 at 3 10 24 pm" src="https://cloud.githubusercontent.com/assets/2593113/19174433/aad0e6e6-8be3-11e6-80de-f30b2943e8c8.png">
<img width="463" alt="screen shot 2016-10-06 at 3 10 43 pm" src="https://cloud.githubusercontent.com/assets/2593113/19174434/b1ece4d4-8be3-11e6-87e4-51bd526b7931.png">
<img width="1440" alt="screen shot 2016-10-06 at 3 16 03 pm" src="https://cloud.githubusercontent.com/assets/2593113/19174438/b71f8678-8be3-11e6-9cca-c6f3314d3f96.png">

**Comment by ichung1** [comment]
Hi Ken, 

Here's 3 concepts I came up with.  The more I look at it, the more I'm leaning towards the first row. The first one is an alert, the second is none, and the third is when the panel is open.    

<img width="142" alt="screen shot 2016-10-10 at 10 09 29 am" src="https://cloud.githubusercontent.com/assets/10854635/19244564/b3142944-8ed1-11e6-92a5-2b16eaa343d0.png">

Here's the alert with a screenshot of the bar:

<img width="279" alt="screen shot 2016-10-10 at 10 09 40 am" src="https://cloud.githubusercontent.com/assets/10854635/19244601/ef282692-8ed1-11e6-9495-48e5bc1a926b.png">

The warning red and orange colors clash quite a bit, I tried separating the two without adding too much white (the 3rd row).  The first row could either be a good starting point or the go to one.  I'll have to think about it more.

**Comment by kenigeer** [comment]
Agree on the color clash. Would it be too radical to go all the way to blue? (This action movie/video game trope would fit well with the Adapt or Die theme.) Also does the empty bell look just a bit too big compared to the "apigee" logo and text in the menu bar:
<img width="1042" alt="screen shot 2016-10-11 at 3 47 14 am" src="https://cloud.githubusercontent.com/assets/2593113/19279039/72e1abd0-8f94-11e6-97b7-de800e669a17.png">

**Comment by brandonscript** [comment]
@kenigeer the asset is @ 2x resolution, so it would appear half that size on the bar itself. Color clash is a real problem - blue would be pretty clashy too though, unless you're just talking about the alert glyph? My vote goes to solid white bell, and then solve for the inner alert glyph color.

**Comment by kenigeer** [comment]
Well I did test it out by downloading the PNG in the comment. Did the 2x reduction to get 28x28. What are the pixel dimensions supposed to be?

I was just talking about the alert glyph (bang in circle).

However, in the first version of this feature, you actually cannot clear any notifications; they persist until they age out. So maybe having a clashy alert you can't get rid of is too much.

**Comment by ichung1** [comment]
Here's a smaller version of the alarms just so it doesn't look freakishly huge.  Lowered to 15x16px.  

Hmm, if we can't clear any notifications, I wonder if we might have to change it up a little.  Agreed on having a clashy alert if you can't get rid of it being too much.

<img width="80" alt="screen shot 2016-10-11 at 2 49 37 pm" src="https://cloud.githubusercontent.com/assets/10854635/19290088/cd69154c-8fc2-11e6-8229-8c45ed5a3316.png">

**Comment by ichung1** [comment]
I’m guessing if we don’t need an alert a user can’t get rid of, we can stick with two different alarms then?

Something along the lines of:
1) Bell with notification
2) Bell without notification

<img width="83" alt="screen shot 2016-10-11 at 3 07 58 pm" src="https://cloud.githubusercontent.com/assets/10854635/19290452/9ecf82dc-8fc4-11e6-8262-1b2f9930f02a.png">

**Comment by ichung1** [comment]
@kenigeer This could be a solution:

<img width="85" alt="screen shot 2016-10-12 at 2 37 20 pm" src="https://cloud.githubusercontent.com/assets/10854635/19328642/70f87790-9089-11e6-93fa-43a7ec9ad868.png">

The more I look at it, the more I think we shouldn't add additional colors, especially if notifications can't be cleared. Something straight forward like this can work as well:

<img width="81" alt="screen shot 2016-10-12 at 2 31 18 pm" src="https://cloud.githubusercontent.com/assets/10854635/19328669/96b316c0-9089-11e6-859d-a234546f50ea.png">

**Comment by ichung1** [comment]
Hey @kenigeer,

Haven't heard back from you regarding this.  I'll go ahead and close if I don't hear back from you.

-in

**Comment by kenigeer** [comment]
I've used it by downloading the PNG, which works fine for my usage. Is it supposed to be added to the font file?

I did notice that the orange background color is slightly off compared to the Apigee menubar. It's 255,75,0 while the menubar is 255,67,0. Is that intentional?

**Comment by brandonscript** [comment]
Let's leave it out of the font file. When integrated with UE, we can add then. 

As for the colour, let's match it (though the menu bar is actually wrong ;)

**Comment by ichung1** [comment]
Closing this request.  We'll add the alarm/notification when integrating with UE.
