### ISSUE TITLE
Snapshot icon

### ISSUE THREAD

**Issue by brandonscript** [apigee-internal/apigee-icons#8]
I think the camera icon isn't really suitable for "state" snapshots; these are more time-based containers than they are relating to photography.

Thinking something like this, from the Pixellove "Time" collection.

<img width="49" alt="screenshot_1662" src="https://cloud.githubusercontent.com/assets/1480253/19177746/b9b27e96-8c00-11e6-8814-1e4977d8aee2.png">

**Comment by MMux** [comment]
mm...let's get @earth2marsh to weigh in on this.

**Comment by earth2marsh** [comment]
"Snapshots" are used like a backup image or a virtual machine state—to communicate a static copy of something. Watch to me connotes a "wait", which seems less appropriate.

**Comment by brandonscript** [comment]
My leading inspiration is exactly that -- VMware uses a modified timer icon to indicate snapshot. Clock needs work but we need to decide if that's the direction we want to go first.

**Comment by MMux** [comment]
also, the watch metaphor could work better in trace, where it's almost like a stopwatch (although i favor harvest times moving hands)
<img width="178" alt="screen shot 2016-10-07 at 2 58 05 pm" src="https://cloud.githubusercontent.com/assets/1907403/19206543/78cd8f1c-8c9e-11e6-93ce-dc54b0361099.png">

**Comment by earth2marsh** [comment]
What about a clock face in a polaroid?

**Comment by earth2marsh** [comment]
I do think a camera is slightly unexpected.

**Comment by ichung1** [comment]
something like this? 
<img width="130" alt="screen shot 2016-10-07 at 3 20 11 pm" src="https://cloud.githubusercontent.com/assets/10854635/19206971/9febadec-8ca1-11e6-97b1-10ad1e5e3529.png">

**Comment by brandonscript** [comment]
I had to look at it three times to realize it wasn't just a plain camera 😊

**Comment by earth2marsh** [comment]
oh, that's very clever

**Comment by ichung1** [comment]
i'll clean it up and throw it in the Sketch file.  Will mark as "done" when finished.  👍

**Comment by MMux** [comment]
nicely!

**Comment by ichung1** [comment]
Created the right most snapshot icon (see slack conversation - screenshot attached) in Sketch file (14pt) in dropbox.

<img width="38" alt="screen shot 2016-10-10 at 2 21 21 pm" src="https://cloud.githubusercontent.com/assets/10854635/19251598/fa39978c-8ef4-11e6-9ce7-15120df270b2.png">

Marking done.
